### ISSUE TITLE
Spelling/ grammar corrections in help texts

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/nmr-star-dictionary#8]
Thank you for all of these great catches. I have put comments after each one.
Eldon

<strike>The following are all in the help text unless otherwise stated:
(The following items are only missing a period at the end of the help sentence: 3, 4, 7, 8, 9, 10, 17, 18, 19, 20, 21, 23)</strike>

<strike>1. Under entry information-Release status for NMR experimental data: "Depositors are encourage to make" should be "encouraged to make".</strike>
Fixed

2. Under entry information-Entry description: "participating in methods development experiments." The p in participating should be capitalized. This help description is not very clear also.
Rewritten - somehow texted became mangled in the dictionary.

<strike>3. Under entry information-Contact person-ORCID: This help text is missing a period at the end of it.
Fixed

4. Under entry information-Contact person-Salutation: This help text is missing a period at the end of it.
Fixed

5. Under entry information-Contact person-Contact person's first name: "The name given the contact person at birth" should be "The name given to the contact person at birth"
Fixed

6. Under entry information-Entry authors-Entry author's first name: "The name given the author at birth" should be "The name given to the author at birth"
Fixed

7. Under Citations-Citation status: This help text is missing a period at the end of it.
Fixed

8. Under Citations-Citation type: This help text is missing a period at the end of it.
Fixed

9. Under Citations-Citation's first page number: This help text is missing a period at the end of it.
Fixed

10. Under Citations-Citation's last page number: This help text is missing a period at the end of it.
Fixed

11. Under Citations-Citation author-Author's first name: "The name given the author at birth" should be "The name given to the author at birth"
Fixed

12. Under Ligands, cofactors, etc.: The PDB link is currently titled "Ligand Depot" but they have changed the name of this to "Ligand Expo" (this can be seen by clicking the link).
Fixed

13. Under Ligands, cofactors, etc.-Image file name: "name of the Image file" should be lower case for consistency so "name of the image file"
Fixed

14. This is relating to the title of a section and no the help menu. Under Molecular entity one of the sections says "Enter the complete polymer sequence (one-letter code) Include all cloning..." It is missing a period and should be "Enter the complete polymer sequence (one-letter code). Include all cloning..."
Fixed - actually in prompt

15. Under Molecular entity-Fragment name: "protein or necleic acid" should be "protein or nucleic acid"
Fixed

16. Under Molecular entity-Enzyme commission number: "Enzyme Commission number" should be lower case for consistency and is missing a period so "Enzyme commission number."
Reworded a bit. "Enzyme Commission" is the name of a group and should be upper cased

17. Under Molecular assembly-Molecular assembly contents-Assembly component name: This help text is missing a period at the end of it.
Fixed

18. Under Molecular assembly-Links to structure, function, or...-Common database abbreviation: This help text is missing a period at the end of it.
Fixed

19. Under Molecular assembly-Molecular assembly component interaction descriptions-Mol 1 entity ID: This help text is missing a period at the end of it.
Fixed

20. Under Molecular assembly-Molecular assembly component interaction descriptions-Mol 2 entity ID: This help text is missing a period at the end of it.
Fixed

21. Under Molecular assembly-Molecular assembly component interaction descriptions-Mol interaction type: This help text is missing a period at the end of it.
Rewritten

22. Under Sample-Concentration value units: "value enter earlier for" should be "value entered earlier for"
Fixed

23. Under Sample content purity-Molecular purity-Val: This help text is missing a period at the end of it.
Fixed

24. Under NMR experiments and samples-Experiment list-Sample label: "was run on an 15N labeled" should be "was run on a 15N labeled"
Not changed. Although written 15N, this is most often read 'N15' and there is always controversy over whether it should be written 'an N' or 'a N' since 'N' is not a vowel, but common usage is 'an NMR'. Seems to roll off the tongue better. Although you will find both in the literature.

25. On the Chemical shift references page all of the "___ chemical shifts deposited" help texts say "After clicking on the 'Save Changes' button," but this button no longer exists due to the auto-save feature. This help text should probably be changed to account for this.
Fixed

26. Under Chemical shift references-Chemical shift reference data-Correction value applied: "An uniform correction" should be "A uniform correction" (I had to look that one up, a bit of goofy grammar rules with vowel and consonant sounds I guess).
Fixed

27. This is relating to the title of a section and no the help menu. Under Assigned chemical shifts one of the sections is "Described the method used..." it should be "Describe the method used..."
Fixed - actually in prompt</stikre>

**Comment by rsiegl** [comment]
I can confirm all of the fixes except point 1 still appears to be unresolved and point 2 still seems to have some odd/unclear wording in it. <strike>While going through these checks I noticed that in the Ligands, cofactors, etc. page the "Chemical compound information" header has `<br>` in it twice also.</strike>

**Comment by elulrich** [comment]
Hi,

I believe I have corrected the additional problems in point 1 and point 2.
Thanks

**Comment by elulrich** [comment]
These updates will not appear until after April 1.

**Comment by jonwedell** [comment]
@elulrich  - The original issue in point 2 appears to be resolved, but there is still a typo in `_Entry.Details`:

contents of the entry beyond that **provide** in other sections

should be

contents of the entry beyond that **provided** in other sections



Verified point 1 is fixed.

**Comment by elulrich** [comment]
Fixed, but will not be released until later when more issues are updated.

**Comment by jonwedell** [comment]
The "contents of the entry beyond that **provide** in other sections" issue still exists in the `_Entry.Details` tag in the most recent dictionary.

**Comment by elulrich** [comment]
All fixed. If new ones are found open a issue.
